Localization = setmetatable({
	['SlashCommand'] = '/ph',
	['SettingsTitle'] = 'PvP Helper',
	['WarsongGulch'] = 'Warsong Gulch',
	['ArathiBasin'] = 'Arathi Basin',
	['AlteracValley'] = 'Alterac Valley',
	['EyeOfTheStorm'] = 'Eye of the Storm',
	['StrandOfTheAncients'] = 'Strand of the Ancients',
	['IsleOfConquest'] = 'Isle of Conquest',
	['TwinPeaks'] = 'Twin Peaks',
	['BattleForGilneas'] = 'The Battle for Gilneas',
	['WarsongGulchMinuteWarning'] = 'The battle for Warsong Gulch begins in 1 minute.',
	['ArathiBasinMinuteWarning'] = 'The Battle for Arathi Basin will begin in 1 minute.',
	['AlteracValleyMinuteWarning'] = '1 minute until the battle for Alterac Valley begins.',
	['EyeOfTheStormMinuteWarning'] = 'The battle begins in 1 minute!',
	['StrandOfTheAncientsMinuteWarning'] = 'The battle for the Strand of the Ancients begins in 1 minute.',
	['IsleOfConquestMinuteWarning'] = 'The battle will begin in 60 seconds.',
	['TwinPeaksMinuteWarning'] = 'The battle begins in 1 minute.',
	['BattleForGilneasMinuteWarning'] = 'The battle will begin in 1 minute.',
	['AnnounceSelf'] = 'Track AFK players and announce them to yourself',
	['AnnounceRaid'] = 'Track AFK players and announce them to the raid',
	['Achievement'] = 'Track unfinished achievements while in battle',
	['PrimarySpec'] = 'Warn if queueing for battle in primary spec',
	['SecondarySpec'] = 'Warn if queueing for battle in secondary spec',
	['ShowZero'] = 'Show notification if no one is AFK',
	['ShowMeta'] = 'Display the battleground meta achievements',
	['WrongSpec'] = 'You are not in the right spec for PvP',
	['GearTrack'] = 'Warn if queueing for battle without PvP gear on',
	['WrongGear'] = 'You are not wearing the right gear for PvP',
	['Report'] = ' was reported AFK',
	['Check'] = 'AFK Check: ',
	['Reported'] = ' Reported',
	['Invalid'] = 'Invalid Command',
	['Version'] = 'Version: ',
	['Loaded'] = 'PvP Helper loaded, type /ph for the control panel.',
	['HelpUs'] = 'If any of the gear recommended is mismatched, mispelled, does not exist or does not clear off the list after you bought it, or if you are getting false positives with the AFK tracking, leave a comment on our page at www.curse.com.',
	['TooLow'] = 'You must reach level 85 to use gear evaluation.',
	['NoTalent'] = 'You must select a talent tree to use the evaluation.',
	['DesignedBy'] = 'Designed by Speedbumps (Garrosh-US) and Tawnee (Exodar-US)',
	['OldVersion'] = 'Your version of PvP Helper is outdated',
	['NewVersion'] = ' is available at www.curse.com',
	['Help'] = 'visit www.curse.com for help',
	['Avatar'] = '<PvP Helper> ',
	['GearEvaluation'] = 'Gear Evaluation',
	['Options'] = 'Options',
	['GoodJob'] = 'You have the best gear available this season.',
	['ShamanHit'] = 'You may need to forge a few items to reach the limit on hit rating.',
	['PriestHit'] = 'You will need two points in the talent "Twisted Faith" to reach the limit on hit rating.',
	['PaladinHit'] = 'You will need two points in the talent "Enlightened Judgements" to reach the limit on hit rating.',
	['DruidHit'] = 'You will need two points in the talent "Balance of Power" to reach the limit on hit rating.',
	['YouAre'] = 'You are ',
	['LowSpen'] = ' points below the spell penetration cap.',
	['LowExp'] = ' points below the expertise cap.',
	['LowHit'] = ' points below the hit penetration cap.',
	['Crafted'] = '(Crafted)',
	['Honor'] = 'Honor',
	['Conquest'] = 'Conquest',
	['Good'] = 'Good: ',
	['Better'] = 'Better: ',
	['Best'] = 'Best: ',
	['UnrecognizedItem'] = 'Please report this error: No English translation for the item '},
	{
	__index = function(self, key)
		ChatFrame3:AddMessage('Please localize: '..tostring(key))
		rawset(self, key, key)
		return key
	end }
)




